servers:
  web:
    - 192.168.0.200

proxy:
  hosts:
    - mrwatchdog.com
    - production-local.mrwatchdog.com

env:
  clear:
    ASPNETCORE_ENVIRONMENT: "Production"

accessories:
  db:
    host: 192.168.0.200
