proxy:
  host: mrwatchdog.com

env:
  clear:
    ASPNETCORE_ENVIRONMENT: "Production"

accessories:
  db-production:
    image: postgres:18.0-alpine
    host: 192.168.0.190
    port: "127.0.0.1:5432:5432"
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - PGPORT

